import { glob } from 'glob';
import { spawn } from 'child_process';
import path from 'path';
import os from 'os';
import fs from 'fs/promises';

// Configuration matching the workflow environment
const CONFIG = {
    distDir: 'dist',
    domain: process.env.DOMAIN || 'perito.barcelona',
    certFile: '.certs/cert.pem',
    keyFile: '.certs/privkey.pem',
    // Hardcoded as per workflow fixes
    // Use env vars or dynamic defaults based on domain
    certUrl: process.env.CERT_URL || `https://${process.env.DOMAIN || 'perito.barcelona'}/cert.cbor`,
    validityUrl: process.env.VALIDITY_URL || `https://${process.env.DOMAIN || 'perito.barcelona'}/resource.validity.msg`,
    expire: '168h'
};

console.log('🔧 SXG Configuration:');
console.log(`   Domain: ${CONFIG.domain}`);
console.log(`   Cert URL: ${CONFIG.certUrl}`);
console.log(`   Validity URL: ${CONFIG.validityUrl}`);

// Concurrency limit - aggressive but safe for Go binaries
const LIMIT = Math.max(4, os.cpus().length * 2);

function runCommand(cmd, args) {
    return new Promise((resolve, reject) => {
        const p = spawn(cmd, args);
        let stderr = '';

        p.stderr.on('data', (d) => {
            stderr += d.toString();
        });

        p.on('close', (code) => {
            if (code === 0) {
                resolve();
            } else {
                reject(new Error(`Command failed with code ${code}: ${stderr}`));
            }
        });

        p.on('error', (err) => {
            reject(err);
        });
    });
}

async function main() {
    console.log(`🚀 Starting SXG generation for ${CONFIG.domain}...`);
    console.log(`   Concurrency: ${LIMIT}`);

    // Copy cert.cbor (generated by previous workflow step) to dist to ensure deployment updates it
    console.log('📦 Copying cert.cbor to dist...');
    try {
        await fs.copyFile('cert.cbor', path.join(CONFIG.distDir, 'cert.cbor'));
        console.log('   ✅ cert.cbor copied to dist.');
    } catch (err) {
        console.warn('   ⚠️ Could not copy cert.cbor from root. Verify previous step generated it.', err.message);
    }

    // Find all HTML files
    const files = await glob(`${CONFIG.distDir}/**/*.html`, {
        ignore: [`${CONFIG.distDir}/404.html`, `${CONFIG.distDir}/admin/**`]
    });

    console.log(`   Found ${files.length} HTML files to sign.`);

    let processedCount = 0;
    let errorCount = 0;
    const errors = [];

    // Queue iterator
    let index = 0;

    const processNext = async () => {
        while (index < files.length) {
            const i = index++;
            const file = files[i];

            try {
                // Compute URI
                let relativePath = path.relative(CONFIG.distDir, file).split(path.sep).join('/');

                let uriPath = relativePath;
                if (uriPath.endsWith('/index.html')) {
                    // dist/foo/index.html -> foo/
                    uriPath = uriPath.replace(/\/index\.html$/, '/');
                    if (uriPath === 'index.html') uriPath = ''; // Root
                } else if (uriPath === 'index.html') {
                    uriPath = '';
                }

                // Ensure trailing slash for directories if needed, or keep as is.
                // Workflow logic was:
                // if [[ "$html_file" == *"/index.html" ]]; then uri="${html_file%/index.html}/"; fi
                // My logic above handles this.

                const uri = `https://${CONFIG.domain}/${uriPath}`;
                const outputFile = `${file}.sxg`;

                // Run gen-signedexchange
                // gen-signedexchange -uri ... -content ...

                // Set date to 1 hour ago to avoid "invalid timestamp" (clock skew) errors
                const date = new Date();
                date.setHours(date.getHours() - 1);

                const args = [
                    '-uri', uri,
                    '-content', file,
                    '-certificate', CONFIG.certFile,
                    '-privateKey', CONFIG.keyFile,
                    '-certUrl', CONFIG.certUrl,
                    '-validityUrl', CONFIG.validityUrl,
                    '-date', date.toISOString(),
                    '-o', outputFile,
                    '-expire', CONFIG.expire
                ];

                await runCommand('gen-signedexchange', args);
                processedCount++;

                // Progress indicator (dots)
                if (processedCount % 10 === 0) process.stdout.write('.');

            } catch (err) {
                process.stdout.write('X');
                // errorCount++; // Don't fail immediately
                errors.push({ file, error: err.message });
            }
        }
    };

    // Start workers
    const workers = [];
    for (let i = 0; i < LIMIT; i++) {
        workers.push(processNext());
    }

    await Promise.all(workers);

    console.log('\n\n✅ Generation complete.');
    console.log(`   Success: ${processedCount}`);
    console.log(`   Errors:  ${errors.length}`);

    if (errors.length > 0) {
        console.error('❌ Errors occurred:');
        errors.forEach(e => console.error(`   ${e.file}: ${e.error}`));
        process.exit(1);
    }
}

main().catch(err => {
    console.error('Fatal error:', err);
    process.exit(1);
});
